version: '3.1'
services:
  db:
    image: mariadb
    container_name: mariadb-piwigo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: #MakeYourOwnStrongPassword
      MYSQL_DATABASE: piwigo
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: #MakeYourOwnStrongPassword
    volumes:
      - /portainer/Files/AppData/Config/Piwigo/mariadb:/var/lib/mysql
    
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /portainer/Files/AppData/Config/Piwigo/config:/config
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 8581:80
    restart: unless-stopped
