version: "3.8"
services:
  resume_app:
    image: martadinata666/reactive-resume:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=resume_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=reactiveresume
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_TIME=604800
      - STORAGE_S3_ENABLED=false
    ports:
      - 7680:80
      - 3000:3000
    networks:
      - reactiveresume
    volumes:
# Make sure to change the path to the left of the colon to match your folder structure.
      - /portainer/Files/AppData/Config/react-resume/assets:/home/debian/reactiveresume/server/dist/assets #photo and export storage
    restart: unless-stopped

  resume_db:
    image: postgres:13
    environment:
      - PUID=1000
      - PGID=1000
#      - POSTGRES_SSL_CERT=
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=reactiveresume
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/react-resume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - reactiveresume

networks:
  reactiveresume:
    name: reactiveresume
