version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /portainer/Files/AppData/Config/react-resume/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reactiveresume
      - POSTGRES_USER=reactiveresume
      - POSTGRES_PASSWORD=${DB_PASS}

  server:
    image: amruthpillai/reactive-resume:server-latest
    restart: always
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=http://{IP:3000}
      - PUBLIC_SERVER_URL=http://{IP:3100}
#      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=reactiveresume
      - POSTGRES_USER=reactiveresume
      - POSTGRES_PASSWORD=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
#      - POSTGRES_SSL_CERT=
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_TIME=604800
#      - GOOGLE_CLIENT_SECRET=
#      - GOOGLE_API_KEY=
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
#      - STORAGE_BUCKET=
#      - STORAGE_REGION=
#      - STORAGE_ENDPOINT=
#      - STORAGE_URL_PREFIX=
#      - STORAGE_ACCESS_KEY=
#      - STORAGE_SECRET_KEY=
#      - PDF_DELETION_TIME=
    volumes:
      - /portainer/Files/AppData/Config/react-resume/assets:/home/debian/reactiveresume/server/dist/assets #photo and export storage

  client:
    image: amruthpillai/reactive-resume:client-latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://{IP:3000}
      - PUBLIC_SERVER_URL=http://{IP:3100}
#      - PUBLIC_GOOGLE_CLIENT_ID=
