version: '3.3'
services:
  ward:
    image: antonyleons/ward:latest
    restart: unless-stopped
    container_name: ward
    ports:
     - '4000:4000'
    environment:
     - WARD_PORT=4000
     - WARD_THEME=dark
     - WARD_NAME=Docker-VM
    privileged: true
