version: '3.3'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: 'ghcr.io/alexjustesen/speedtest-tracker:v0.11.17'
    ports:
    - '8087:80'
    - '8448:443'
    environment:
    - PUID=1000
    - PGID=1000
    - DB_CONNECTION=mysql
    - DB_HOST=db
    - DB_PORT=3306
    - DB_DATABASE=speedtest_tracker
    - DB_USERNAME=speedy
    - DB_PASSWORD= #MakeYourOwnStrongPassword
    - TZ=America/New_York
    volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/portainer/Files/AppData/Config/st2/config:/config'
    - '/portainer/Files/AppData/Config/st2/web:/etc/ssl/web'
    restart: unless-stopped
    depends_on:
    - db
    
  db:
    image: mariadb:10
    restart: always
    environment:
    - MARIADB_DATABASE=speedtest_tracker
    - MARIADB_USER=speedy
    - MARIADB_PASSWORD= #MakeYourOwnStrongPassword
    - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
    - /portainer/Files/AppData/Config/st2/db:/var/lib/mysql
