services: 
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    container_name: semaphore_db
    volumes:
      - /portainer/Files/AppData/Config/semaphore/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
  semaphore:
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    container_name: semaphore
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${DB_USER}
      SEMAPHORE_DB_PASS: ${DB_PASSWORD}
      SEMAPHORE_DB_HOST: ${DB_HOST} #  choices are mysql & postgres
      SEMAPHORE_DB_PORT: ${DB_PORT} # 3306 for mysql, 5432 for postgres
      SEMAPHORE_DB_DIALECT: ${DB_HOST} # choices are mysql & postgres
      SEMAPHORE_DB: ${DB_NAME}
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore/common/repositories
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME} #first/last name or handle, whatever works for you
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${ADMIN_USERNAME}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ACCESS_KEY_ENC} # run "head -c32 /dev/urandom | base64 from CLI of host OS
      TZ: ${TZ}

    volumes:
      - /portainer/Files/AppData/Config/semaphore/inventory/:/inventory:ro
      - /portainer/Files/AppData/Config/semaphore/authorized-keys/:/authorized-keys:ro
      - /portainer/Files/AppData/Config/semaphore/config/:/home/semaphore:rw
      - /portainer/Files/AppData/Config/semaphore/.ssh/:/home/semaphore/.ssh:rw #needs to "rw" at first but once ssh keys are created, it will need to be set back to "ro".
      - /portainer/Files/AppData/Config/semaphore/.ssh/known_hosts:/home/semaphore/known_hosts:rw
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - ${DB_HOST} # for postgres, change to: postgres
