version: "3"
services:
  endlessh:
    container_name: endlessh
    image: shizunge/endlessh-go:latest
    restart: unless-stopped
    #user: root
    command:
      - "-logtostderr"
      - "-v=1"
      - "-geoip_supplier=max-mind-db"
      - "-max_mind_db=/geo-data/GeoLite2-City.mmdb"
      - -interval_ms=1000
      - -enable_prometheus
    ports:
      - 2222:2222 # SSH port
      - 2112:2112 # Prometheus metrics port
    volumes:
      - /portainer/Files/AppData/Config/endlessh-go/geo-data/:/geo-data/:ro # geoip data

  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:v5
    container_name: geoipupdate
    restart: unless-stopped
    security_opt: [ "no-new-privileges:true" ]
    volumes:
      - /portainer/Files/AppData/Config/endlessh-go/geo-data/:/usr/share/GeoIP/
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=72
      - GEOIPUPDATE_ACCOUNT_ID=${MAXMIND_ID}
      - GEOIPUPDATE_LICENSE_KEY=${MAXMIND_KEY}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: "1000:1000"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    ports:
      - 9090:9090
    volumes:
      - /portainer/Files/AppData/Config/endlessh-go/prometheus.yml:/etc/prometheus/prometheus.yml
      - /portainer/Files/AppData/Config/endlessh-go/prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000:1000"
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/endlessh-go/grafana/grafana_var:/var/lib/grafana/
      - /portainer/Files/AppData/Config/endlessh-go/grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
  
